spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Bank Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      akhilfrancis:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
#    here default means this config applies to all circuit breakers . If I give a name instead of default then only
#    that ciruit breaker will behave with that config
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 4s