apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  labels:
    app: mysql
data:
  init.sql: |
    {{- range .Values.databases }}
    CREATE DATABASE IF NOT EXISTS {{ . }};
    {{- end }}
